name: TPPlus
author: MDCreator
version: 1.13
description: A simple, custom TP, spawn, and home plugin.

main: net.mdcreator.tpplus.TPPlus

commands:
    home:
        description: The base home command
        aliases: [hoem]
        usage: |
            §8[§9TP+§8]§7 /home usage
            §7/home help §8show this menu
            §7/home §8go home
            §7/home set §8set your home
            §7/home set bed §8set your home to your bed
            §7/home list §8list all homes, §2open §8or §4closed
            §7/home open §2open §8your home to others
            §7/home close §4closed §8your home
            §5Tip: §7You can use the first letters of someone's name as their name §8(e.g. 'not' for 'notch')
            §5Tip: §7If you are op, you can go to anyone's closed home
            §7/home [player] §8go to [player]'s open home
    tele:
        description: The base TP command
        usage: |
            §8[§9TP+§8]§7 /tele usage
            §7/tele help §8show this menu
            §5Tip: §7You can use the first letters of someone's name as their name §8(e.g. 'not' for 'notch')
            §5Tip: §7If you are op, the other person does not need to accept you
            §7/tele [player] §8request tp to [player]
            §7/tele accept [player] §8accept tp from [player]
    spawn:
        description: The base spawn command
        usage: |
            §8[§9TP+§8]§7 /spawn usage
            §7/spawn §8go to spawn
            §7/spawn set §8set a new spawn(only if OP)
    tpplus:
        description: The base plugin command
        usage: |
            §8[§9TP+§8]§7 /tpplus usage
            §7/tpplus §8display info
            §7/tpplus update §8automatically update the plugin